# Generated by Django 5.2.7 on 2026-09-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('gateway', '0002_gatewaydevice_android_version_and_more'),
        ('smsgateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundsms',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='The clinic associated with this inbound message.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_sms', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='The clinic that originated this SMS message.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sms_messages', to='clinics.clinic'),
        ),
        migrations.AddIndex(
            model_name='smsmessage',
            index=models.Index(fields=['clinic', 'status'], name='smsgateway__clinic__0454ed_idx'),
        ),
    ]
