# Generated by Django 5.2.7 on 2026-04-28 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_rebookinglink'),
        ('clinics', '0014_alter_clinic_phone_alter_location_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Date of the note')),
                ('start_time', models.TimeField(help_text='Start time of the note')),
                ('end_time', models.TimeField(help_text='End time of the note')),
                ('message', models.TextField(help_text='Note content displayed on the calendar')),
                ('clinic', models.ForeignKey(help_text='Clinic branch this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notes', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_notes_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_notes_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_notes',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['clinic', 'date'], name='calendar_no_clinic__d6ed6e_idx'), models.Index(fields=['date'], name='calendar_no_date_68c8bb_idx')],
            },
        ),
    ]
