# Generated by Django 5.2.7 on 2026-05-26 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_appointment_booking_source'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarnote',
            name='practitioner',
            field=models.ForeignKey(blank=True, help_text='Practitioner this note is scoped to (null = clinic-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_notes', to='clinics.practitioner'),
        ),
    ]
