# Generated by Django 5.2.7 on 2026-07-17 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_appointmentcanceltoken'),
        ('patients', '0029_patientcase_approved_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_case',
            field=models.ForeignKey(blank=True, help_text='The patient case this appointment is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_appointments', to='patients.patientcase'),
        ),
    ]
