"""
Centralized branding configuration for the PMS backend.
"""

SYSTEM_BRANDING = {
    'company_name': 'Malasakit Medical Systems',
    'short_name': 'Malasakit',
    'powered_by': 'Powered by Malasakit Medical Systems',
    'copyright': '© 2026 Malasakit Medical Systems',
    'support_email': 'support@malasakitsolutions.com',
    'website': 'https://malasakitsolutions.com',
    
    # Text injected automatically into system-generated document footers
    'generated_by': 'This is generated by Malasakit Medical Systems',
}
