# Generated by Django 5.2.7 on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('clinics', '0019_rename_clinic_cons_clinic__idx_clinic_cons_clinic__421572_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliniccommunicationsettings',
            name='dna_followup_delay_hours',
            field=models.PositiveIntegerField(default=0, help_text='Hours to wait after DNA before sending follow-up (0 = immediate).'),
        ),
    ]