# Generated by Django 5.2.7 on 2026-05-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_services', '0002_service_assigned_practitioners'),
        ('clinics', '0017_alter_cliniccommunicationsettings_booking_confirmation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discipline',
            field=models.CharField(choices=[('OCCUPATIONAL_THERAPY', 'Occupational Therapy'), ('SPEECH_LANGUAGE_PATHOLOGIST', 'Speech Language Pathologist'), ('PHYSICAL_THERAPY', 'Physical Therapy'), ('OSTEOPATHY', 'Osteopathy'), ('DENTISTRY', 'Dentistry'), ('MD_GENERAL_PRACTITIONER', 'MD: General Practitioner')], default='OCCUPATIONAL_THERAPY', help_text='Practitioner discipline this service is assigned to.', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='assigned_practitioners',
            field=models.ManyToManyField(blank=True, help_text='[Legacy] Practitioners who offer this service. Use discipline instead.', related_name='services', to='clinics.practitioner'),
        ),
    ]
