export interface ClinicBranch {
  id: number;
  name: string;
  branch_code: string | null;   // read-only, auto-generated by backend
  is_main_branch: boolean;
  is_branch: boolean;
  parent_clinic: number | null;
  parent_name: string | null;
  is_active: boolean;
  city: string;
  province: string;
  email?: string;
  phone?: string;
  address?: string;
  postal_code?: string;
  website?: string;
  tin?: string;
  custom_location?: string;
  latitude?: string | null;
  longitude?: string | null;
  logo?: string | null;
  email_notifications_enabled?: boolean;
  sms_notifications_enabled?: boolean;
}

export interface ClinicBranchesResponse {
  branches: ClinicBranch[];
  main_clinic_id: number;
}

export interface CreateBranchData {
  name: string;
  // branch_code intentionally omitted — auto-generated by backend
  email: string;
  phone: string;
  address: string;
  city: string;
  province: string;
  postal_code: string;
  website?: string;
  tin?: string;
  custom_location?: string;
  latitude?: number;
  longitude?: number;
  email_notifications_enabled?: boolean;
  sms_notifications_enabled?: boolean;
}