# Generated by Django 5.2.7 on 2026-05-31 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payment_bank_name'),
        ('clinics', '0017_alter_cliniccommunicationsettings_booking_confirmation_method_and_more'),
        ('patients', '0023_alter_patient_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeingDebtEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=50)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('category', models.CharField(choices=[('CONSULTATION', 'Consultation'), ('TREATMENT', 'Treatment'), ('INVOICE', 'Invoice'), ('INSURANCE', 'Insurance'), ('CORPORATE', 'Corporate Account'), ('OTHER', 'Other')], default='INVOICE', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('WRITTEN_OFF', 'Written Off')], db_index=True, default='OPEN', max_length=20)),
                ('bucket', models.CharField(choices=[('CURRENT', 'Current'), ('0_30', '1-30 Days'), ('31_60', '31-60 Days'), ('61_90', '61-90 Days'), ('90_PLUS', '90+ Days')], db_index=True, default='CURRENT', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ageing_debt_entries', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_debt_entries', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_debt_entries', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ageing_debt_entries', to='patients.patient')),
            ],
            options={
                'db_table': 'ageing_debt_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='ageing_debt_clinic__2d4eda_idx'), models.Index(fields=['patient', 'status'], name='ageing_debt_patient_0bb432_idx'), models.Index(fields=['bucket'], name='ageing_debt_bucket_16d514_idx'), models.Index(fields=['due_date'], name='ageing_debt_due_dat_d2e374_idx')],
            },
        ),
    ]
