# Generated by Django on 2026-04-19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.subscriptions.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'plan',
                    models.CharField(
                        choices=[('TRIAL', 'Trial'), ('MONTHLY', 'Monthly')],
                        default='TRIAL',
                        max_length=20,
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('ACTIVE', 'Active'),
                            ('EXPIRED', 'Expired'),
                            ('CANCELLED', 'Cancelled'),
                        ],
                        default='ACTIVE',
                        max_length=20,
                    ),
                ),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'end_date',
                    models.DateTimeField(default=apps.subscriptions.models.default_trial_end_date),
                ),
                ('is_trial', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscription',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date'], name='subs_status_end_idx'),
        ),
    ]
