# Generated by Django 5.2.7 on 2026-09-27 15:32

import apps.subscriptions.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_clinic_subscriptions(apps, schema_editor):
    """
    Backfill migration:
    1. Associates existing subscriptions with their clinic's main practice.
    2. Upgrades any 'MONTHLY' legacy plan to 'STARTER'.
    3. Sets proper default limits (clinician_limit=4, branch_limit=1, additional_branches=0, commitment_months=12).
    4. Ensures every existing root clinic has an active Subscription.
    """
    Subscription = apps.get_model('subscriptions', 'Subscription')
    Clinic = apps.get_model('clinics', 'Clinic')
    User = apps.get_model('accounts', 'User')

    # Update existing subscriptions
    for sub in Subscription.objects.all():
        if sub.plan == 'MONTHLY':
            sub.plan = 'STARTER'
        if not sub.clinician_limit:
            sub.clinician_limit = 4
        if not sub.branch_limit:
            sub.branch_limit = 1
        if not sub.commitment_months:
            sub.commitment_months = 12

        # Link to main clinic if user belongs to one
        if not sub.clinic_id and sub.user_id:
            try:
                user = User.objects.get(pk=sub.user_id)
                if user.clinic_id:
                    clinic = Clinic.objects.get(pk=user.clinic_id)
                    main_clinic = clinic.parent_clinic if clinic.parent_clinic_id else clinic
                    if not Subscription.objects.filter(clinic_id=main_clinic.id).exists():
                        sub.clinic_id = main_clinic.id
            except Exception:
                pass
        sub.save()

    # Ensure every main clinic has a Subscription
    main_clinics = Clinic.objects.filter(parent_clinic__isnull=True, is_deleted=False)
    for clinic in main_clinics:
        if not Subscription.objects.filter(clinic_id=clinic.id).exists():
            admin_user = User.objects.filter(clinic_id=clinic.id, roles__contains=['ADMIN']).first()
            if not admin_user:
                admin_user = User.objects.filter(clinic_id=clinic.id).first()
            now = django.utils.timezone.now()
            Subscription.objects.create(
                clinic=clinic,
                user=admin_user,
                plan='TRIAL',
                status='ACTIVE',
                is_trial=True,
                billing_cycle='MONTHLY',
                clinician_limit=4,
                branch_limit=1,
                additional_branches=0,
                commitment_months=12,
                start_date=now,
                end_date=now + django.utils.timezone.timedelta(days=14),
                current_period_start=now,
                current_period_end=now + django.utils.timezone.timedelta(days=14),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('subscriptions', '0002_paymongo_integration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymongopaymentlog',
            name='additional_branches',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymongopaymentlog',
            name='billing_cycle',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='paymongopaymentlog',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paymongo_logs', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='paymongopaymentlog',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paymongopaymentlog',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_logs', to='subscriptions.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='additional_branches',
            field=models.PositiveIntegerField(default=0, help_text='Number of paid additional branch allocations.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='branch_limit',
            field=models.PositiveIntegerField(default=1, help_text='Number of branches included in the base plan.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='clinic',
            field=models.OneToOneField(blank=True, help_text='Main practice clinic this subscription belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='clinician_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum clinician allocations. If null, uses plan default; for Enterprise stores custom limit.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='commitment_months',
            field=models.PositiveIntegerField(default=12, help_text='Minimum commitment duration in months (standard = 12).'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(default=apps.subscriptions.models.default_trial_end_date),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('TRIAL', 'Free Trial'), ('STARTER', 'Starter'), ('GROWTH', 'Growth'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise'), ('MONTHLY', 'Monthly (Legacy)')], default='TRIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who initiated or administers the subscription.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['clinic', 'status'], name='subs_clinic_status_idx'),
        ),
        migrations.RunPython(
            backfill_clinic_subscriptions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
