# Generated by Django 5.2.7 on 2026-04-25 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_clientformrequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientformrequest',
            new_name='client_form_patient_3591bd_idx',
            old_name='client_form_patient_completed_idx',
        ),
    ]
