# Generated by Django 5.2.7 on 2026-05-31 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0017_alter_cliniccommunicationsettings_booking_confirmation_method_and_more'),
        ('patients', '0019_make_emergency_contact_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MONITORING', 'Monitoring'), ('DISCHARGED', 'Discharged'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('referred_by', models.CharField(blank=True, default='', max_length=200)),
                ('referral_info', models.TextField(blank=True, default='')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='patients.patient')),
                ('primary_practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_cases', to='clinics.practitioner')),
            ],
            options={
                'db_table': 'patient_cases',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='patient_cas_patient_512422_idx'), models.Index(fields=['patient', '-created_at'], name='patient_cas_patient_a30867_idx')],
            },
        ),
    ]
