# Generated by Django 5.2.7 on 2026-05-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_patientcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='alert_notes',
            field=models.TextField(blank=True, default='', help_text='Persistent alert notes visible across all sessions for this case.'),
        ),
        migrations.AddField(
            model_name='patientcase',
            name='payer',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private Pay'), ('HMO', 'HMO'), ('INSURANCE', 'Insurance'), ('CORPORATE', 'Corporate')], default='', help_text='Insurance or payment type for this case.', max_length=20),
        ),
    ]
