# Generated by Django 5.2.7 on 2026-07-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_patient_home_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcase',
            name='approved_sessions',
            field=models.IntegerField(blank=True, help_text='Maximum number of approved sessions for this case. Null = unlimited.', null=True),
        ),
    ]
