# Generated by Django 5.2.7 on 2026-07-17 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_patientcase_approved_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCaseSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('ADDED_SESSIONS', 'Added Sessions'), ('REMOVED_SESSIONS', 'Removed Sessions'), ('REMOVED_LIMIT', 'Removed Limit')], max_length=50)),
                ('amount', models.IntegerField(blank=True, help_text='Number of sessions added or removed. Null if limit was removed.', null=True)),
                ('previous_limit', models.IntegerField(blank=True, help_text='The approved_sessions limit before this action', null=True)),
                ('new_limit', models.IntegerField(blank=True, help_text='The approved_sessions limit after this action', null=True)),
                ('patient_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='patients.patientcase')),
                ('user', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_case_session_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
