# Generated by Django 5.2.7 on 2026-05-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_userrolechangelog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('ADMIN_ASSISTANT', 'Admin Assistant'), ('PRACTITIONER', 'Practitioner'), ('STAFF', 'Staff'), ('FINANCE', 'Finance')], default='STAFF', max_length=20),
        ),
    ]
