# Generated by Django 5.2.7 on 2026-05-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rbac_add_admin_assistant_finance_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongroup',
            name='role_template',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('ADMIN_ASSISTANT', 'Admin Assistant'), ('FRONTDESK', 'Frontdesk'), ('PRACTITIONER', 'Practitioner'), ('FINANCE', 'Finance'), ('READ_ONLY', 'Read-Only'), ('CUSTOM', 'Custom')], default='CUSTOM', help_text='Starting template used to seed default permissions.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('ADMIN_ASSISTANT', 'Admin Assistant'), ('PRACTITIONER', 'Practitioner'), ('STAFF', 'Staff'), ('FINANCE', 'Finance'), ('READ_ONLY', 'Read-Only')], default='STAFF', max_length=20),
        ),
    ]
