# Generated by Django 5.2.7 on 2026-09-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_normalize_phone_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_permanently_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='True when an admin permanently purges this user. Releases clinician allocation while preserving historical records.'),
        ),
    ]
