# Generated by Django 5.2.7 on 2026-05-31 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_rename_block_appts_prac_date_idx_block_appoi_practit_35b2d6_idx'),
        ('clinical_templates', '0007_clinicalnote_chart_annotation_data'),
        ('clinics', '0017_alter_cliniccommunicationsettings_booking_confirmation_method_and_more'),
        ('patients', '0020_patientcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalnote',
            name='patient_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes', to='patients.patientcase'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['patient_case'], name='clinical_no_patient_bdf3bc_idx'),
        ),
    ]
