# Generated by Django 5.2.7 on 2026-09-25 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_general_soap(apps, schema_editor):
    ClinicalTemplate = apps.get_model('clinical_templates', 'ClinicalTemplate')
    general_soap_structure = {
        "version": "1.0",
        "sections": [
            {
                "id": "soap_section",
                "title": "",
                "order": 1,
                "fields": [
                    {
                        "id": "body_chart",
                        "type": "chart",
                        "chartType": "body",
                        "label": "Body Chart",
                        "required": False,
                    },
                    {
                        "id": "subjective",
                        "type": "textarea",
                        "label": "Subjective",
                        "placeholder": "Enter subjective observations, patient history, or symptoms...",
                        "required": False,
                        "rows": 4,
                    },
                    {
                        "id": "objective",
                        "type": "textarea",
                        "label": "Objective",
                        "placeholder": "Enter objective findings, vital signs, or physical examination details...",
                        "required": False,
                        "rows": 4,
                    },
                    {
                        "id": "assessment",
                        "type": "textarea",
                        "label": "Assessment",
                        "placeholder": "Enter clinical assessment, diagnostic impression, or analysis...",
                        "required": False,
                        "rows": 4,
                    },
                    {
                        "id": "plan",
                        "type": "textarea",
                        "label": "Plan",
                        "placeholder": "Enter future treatment plan, follow-up, or recommendations...",
                        "required": False,
                        "rows": 4,
                    },
                ],
            }
        ],
    }

    ClinicalTemplate.objects.update_or_create(
        name='General SOAP',
        version=1,
        is_system_template=True,
        defaults={
            'category': 'SOAP',
            'discipline': 'General',
            'description': 'Standardized General SOAP clinical note template available to all clinics.',
            'clinic': None,
            'clinic_branch': None,
            'created_by': None,
            'structure': general_soap_structure,
            'is_active': True,
            'is_archived': False,
        },
    )


def remove_general_soap(apps, schema_editor):
    ClinicalTemplate = apps.get_model('clinical_templates', 'ClinicalTemplate')
    ClinicalTemplate.objects.filter(name='General SOAP', is_system_template=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_templates', '0011_clinicalnote_created_by'),
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaltemplate',
            name='is_system_template',
            field=models.BooleanField(default=False, help_text='System-wide default template available to all clinics'),
        ),
        migrations.AlterField(
            model_name='clinicaltemplate',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='Template is scoped to this clinic. Null indicates a system-wide default template.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_templates', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='clinicaltemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clinical_templates_v2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clinicaltemplate',
            index=models.Index(fields=['is_system_template', 'is_active'], name='clinical_te_is_syst_cde43c_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicaltemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system_template', True)), fields=('name', 'version'), name='unique_system_template_version'),
        ),
        migrations.RunPython(seed_general_soap, remove_general_soap),
    ]
