# Generated by Django 5.2.7 on 2026-09-13 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0023_clinicconsentform_created_by_and_more'),
        ('gateway', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaydevice',
            name='android_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='app_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='clinic',
            field=models.ForeignKey(blank=True, help_text='The clinic this device is paired with. NULL for legacy global gateway.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateway_devices', to='clinics.clinic'),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Designates the pre-existing production gateway (Gateway BNE-LX1).'),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='last_sms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='model_name',
            field=models.CharField(blank=True, help_text='e.g. Samsung Galaxy A15', max_length=100),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='phone_number_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='sim_carrier',
            field=models.CharField(blank=True, help_text='Detected carrier name (e.g. Globe, Smart)', max_length=100),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='sim_slot_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='sim_subscription_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='sms_capable',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DevicePairingSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pairing_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pairing_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('claimed_by_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pairing_sessions', to='gateway.gatewaydevice')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_sessions', to='clinics.clinic')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'status'], name='gateway_dev_clinic__4f0f44_idx'), models.Index(fields=['pairing_token'], name='gateway_dev_pairing_f23c3f_idx'), models.Index(fields=['pairing_code'], name='gateway_dev_pairing_5d3a22_idx')],
            },
        ),
    ]
