# Generated by Django 5.2.7 on 2026-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_gatewaydevice_android_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatewaydevice',
            name='is_charging',
            field=models.BooleanField(blank=True, help_text='True if device is currently plugged into charger', null=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='network_type',
            field=models.CharField(blank=True, help_text='Network transport: WIFI, CELLULAR, NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='signal_strength',
            field=models.IntegerField(blank=True, help_text='Signal strength dBm or bars', null=True),
        ),
        migrations.AddField(
            model_name='gatewaydevice',
            name='sim_carrier_2',
            field=models.CharField(blank=True, help_text='Secondary SIM carrier name', max_length=100),
        ),
        migrations.AlterField(
            model_name='gatewaydevice',
            name='battery_level',
            field=models.IntegerField(blank=True, help_text='Battery percentage (0-100)', null=True),
        ),
    ]
